"""
migrate_sqlite_to_mysql.py
----------------------------
Migrates the SQLite warehouse (built and verified by `python3 run_all.py`)
to MySQL, using PyMySQL's executemany for bulk inserts.

Requirements:
    pip install pymysql cryptography

Run:
    export MYSQL_URL="mysql://warehouse:warehouse@localhost:3306/ecommerce_dw"
    python3 migrate_sqlite_to_mysql.py

This mirrors postgres_migration/migrate_sqlite_to_postgres.py closely on
purpose — same structure, same table order — so the two are easy to
compare. The real differences between the two migrations, found by
actually running both against real servers rather than assumed:

  - psycopg2's `execute_values` has no MySQL equivalent; PyMySQL's
    `executemany` is the closest tool and is what's used below. It's
    slower per-row than Postgres's COPY-style bulk insert, so this script
    batches manually (`INSERT_BATCH_SIZE`) rather than relying on the
    driver to do it efficiently.
  - `sale_id`/`review_id` are AUTO_INCREMENT in MySQL (vs BIGSERIAL in
    Postgres) — same idea, different keyword, and the migration still
    excludes the SQLite-assigned `sale_id` from the INSERT so MySQL
    assigns its own (`review_id` IS carried over as-is here since
    `fact_reviews`'s ids come from the source JSON, not autogenerated —
    see schema_mysql.sql).
  - MySQL's `SET FOREIGN_KEY_CHECKS = 0/1` (used inside schema_mysql.sql
    to drop tables in any order) has no Postgres equivalent; Postgres
    used `DROP TABLE ... CASCADE` instead — two different mechanisms for
    the same "let me drop these out of dependency order" problem.
"""
import os
import sqlite3
import sys

try:
    import pymysql
except ImportError:
    print("Install the MySQL driver first: pip install pymysql cryptography")
    sys.exit(1)

SQLITE_PATH = os.path.join(os.path.dirname(__file__), "..", "database", "warehouse.db")
SCHEMA_PATH = os.path.join(os.path.dirname(__file__), "schema_mysql.sql")

# fact_reviews only exists if etl/process_reviews.py has been run (it's an
# optional step in run_all.py — see --skip-reviews).
TABLES_ORDER = ["dim_customer", "dim_product", "dim_date", "fact_sales", "fact_reviews"]
AUTO_INCREMENT_COLUMNS = {"fact_sales": "sale_id"}  # excluded from INSERT; MySQL assigns it
INSERT_BATCH_SIZE = 2000


def get_mysql_connection():
    url = os.environ.get("MYSQL_URL")
    if not url:
        raise RuntimeError(
            'Set MYSQL_URL first, e.g.:\n'
            '  export MYSQL_URL="mysql://warehouse:warehouse@localhost:3306/ecommerce_dw"'
        )
    # mysql://user:pass@host:port/db  ->  pymysql.connect(...)
    from urllib.parse import urlparse
    p = urlparse(url)
    return pymysql.connect(
        host=p.hostname or "localhost",
        port=p.port or 3306,
        user=p.username,
        password=p.password or "",
        database=p.path.lstrip("/"),
        autocommit=False,
    )


def apply_schema(conn):
    with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
        raw = f.read()
    # Strip full-line `--` comments before splitting on `;` — a naive
    # "split on ; then drop chunks that start with --" breaks the moment
    # a comment *contains* a semicolon anywhere (a real bug hit once while
    # writing this: a comment about MySQL syntax had a semicolon in an
    # example sentence and corrupted the next statement). Stripping
    # comment lines first avoids that class of bug entirely.
    lines = [ln for ln in raw.splitlines() if not ln.strip().startswith("--")]
    statements = [s.strip() for s in "\n".join(lines).split(";") if s.strip()]
    with conn.cursor() as cur:
        for stmt in statements:
            cur.execute(stmt)
    conn.commit()
    print("Applied MySQL schema.")


def migrate_table(sqlite_conn, mysql_conn, table_name: str):
    cur_sqlite = sqlite_conn.cursor()
    cur_sqlite.execute(f"SELECT * FROM {table_name}")
    columns = [d[0] for d in cur_sqlite.description]

    skip_col = AUTO_INCREMENT_COLUMNS.get(table_name)
    insert_columns = [c for c in columns if c != skip_col]
    col_indices = [columns.index(c) for c in insert_columns]

    placeholders = ", ".join(["%s"] * len(insert_columns))
    col_list = ", ".join(insert_columns)
    query = f"INSERT INTO {table_name} ({col_list}) VALUES ({placeholders})"

    total = 0
    with mysql_conn.cursor() as cur_mysql:
        while True:
            rows = cur_sqlite.fetchmany(INSERT_BATCH_SIZE)
            if not rows:
                break
            values = [tuple(row[i] for i in col_indices) for row in rows]
            cur_mysql.executemany(query, values)
            total += len(rows)
    mysql_conn.commit()
    print(f"  {table_name:<15} -> migrated {total:,} rows")


def main():
    print("Migrating SQLite -> MySQL...")

    sqlite_conn = sqlite3.connect(SQLITE_PATH)
    mysql_conn = get_mysql_connection()

    try:
        apply_schema(mysql_conn)

        print("\nMigrating tables in FK-safe order:")
        for table in TABLES_ORDER:
            exists = sqlite_conn.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,)
            ).fetchone()
            if exists:
                migrate_table(sqlite_conn, mysql_conn, table)
            else:
                print(f"  {table:<15} -> skipped (not present in SQLite)")

        print("\nDone.")
    finally:
        sqlite_conn.close()
        mysql_conn.close()


if __name__ == "__main__":
    main()
